services:
  bot:
    build: .
    environment:
     - BOT_TOKEN=${BOT_TOKEN}
     - DB_URI=mongo
    restart: unless-stopped
  mongo:
    image: mongo
    ports:
     - "127.0.0.1:27017:27017"
    restart: always
